# ========================================================
# すべてのサーバのFirewalldをストップする。(firewalldstop.yml)
# playbookの処理中は一旦すべて止めて最後に起動する
# ========================================================
- hosts: adminserv01
  sudo: no
  remote_user: root
  tasks:
    # ========================================================
    # Firewallはサーバ設定完了後に設定する為一旦ストップしておきます。
    # すべてのサーバ設定が終わったら起動します。
    # ========================================================
    - name: ファイヤーウォールをストップする
      service: name=firewalld enabled=true state=stopped
      ignore_errors: True

