# ========================================================
# nmon設定(nmon.yml)
# ========================================================
---
- hosts: all
  sudo: no
  vars_files:
    - ../vars/filedir.yml
  remote_user: root
  tasks:
    # ========================================================
    # NMONコマンドはyumを使わず解凍して使用する。
    # 冪等性を保つため既に/bin/nmonがある場合は何もしない
    # ========================================================
    - name: nmonの存在確認(以下すべて存在してない場合のみ実行)
      stat: path=/bin/nmon
      register: nmonext

    # ========================================================
    # NMONコマンドのtar.gzはダウンロード済であることとする。
    # 既にダウンロードしたnmonはNFSサーバをマウントした
    # /var/opt/data/nfs/配下に配置済。
    # tarコマンドにて回答して /bin/配下にコピーする
    # ========================================================
    - name: 展開
      command: tar zxvf /var/opt/data/nfs/os/installer/centos7.tar.gz -C /bin
      when: not nmonext.stat.exists

    # ========================================================
    # NMONコマンドの名前が展開しただけではnmon_x86_64_centos7
    # となる為nmonに変更
    # ========================================================
    - name: 名前を変更
      command: mv /bin/nmon_x86_64_centos7 /bin/nmon
      when: not nmonext.stat.exists

    # ========================================================
    # パーミッションとオーナをroot:root 755に変更する
    # ========================================================
    - name: パーミッションを変更
      file:
        group=root mode=0755 owner=root path=/bin/nmon state=file
      when: not nmonext.stat.exists
