# ========================================================
# Rubyをインストール(ruby.yml)
# ========================================================
- hosts: all
  sudo: no
  remote_user: root
  tasks:
    # ========================================================
    # rubyが既にインストールされている場合は実行しない
    # 為の確認コマンド
    # ========================================================
    - name: Rubyの存在確認
      shell: which ruby
      register: ruby_install
      failed_when: ruby_install.rc not in [0, 1]

    # ========================================================
    # 以下のRubyがインストールされている場合は設定しない
    # ========================================================

    # ========================================================
    # githubよりrbenv(Rubyの複数バージョン切替)をクローンする
    # ========================================================
    - name: gitからrbenvをクローンする
      git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
      when: ruby_install.rc == 1

    # ========================================================
    # githubよりruby-build(rubyインストーラ)をクローンする
    # ========================================================
    - name: rbenvビルドプラグインをクローンする
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/root/.rbenv/plugins/ruby-build
      when: ruby_install.rc == 1

    # ========================================================
    # rbenv init置換する
    # ========================================================
    - name: profile_init.sh内のREPLACE_EXECRBENVをrbenv initに置換する
      replace:  dest=/etc/profile.d/profile_init.sh regexp="^#REPLACE_EXECRBENV" replace='eval "$(rbenv init -)" >/dev/null 2>&1'
      when: ruby_install.rc == 1

    # ========================================================
    # profile_init.shを再読み込み
    # ========================================================
    - name: bashの実行
      shell: /etc/profile.d/profile_init.sh
      when: ruby_install.rc == 1

    # ========================================================
    # ruby 2.1.8バージョンをインストールする
    # ========================================================z
    - name: 2.1.8のインストール
      command: rbenv install 2.1.8
      when: ruby_install.rc == 1

    # ========================================================
    # ruby 2.2.4バージョンをインストールする
    # ========================================================z
    - name: 2.2.4のインストール
      command: rbenv install 2.2.4
      when: ruby_install.rc == 1

    # ========================================================
    # rbenv rehashを行う
    # ========================================================z
    - name: rehashを行う
      command: rbenv rehash
      when: ruby_install.rc == 1

    # ========================================================
    # ruby 2.1.8をデフォルトに設定
    # ========================================================z
    - name: 2.1.8をデフォルトに設定
      command: rbenv global 2.1.8
      when: ruby_install.rc == 1

    # ========================================================
    # rbenv rehashを行う
    # ========================================================z
    - name: rehashを行う
      command: rbenv rehash
      when: ruby_install.rc == 1





