# ========================================================
# adminserv01にjenkinsをインストールする(jenkinsmvn,yml)
# ========================================================
---
- hosts: adminserv01
  sudo: no
  vars_files:
    - ../vars/filedir.yml
  remote_user: root
  tasks:
    # ========================================================
    # mavenをunzipして/opt配下に配置する
    # ========================================================
    - name: Mavenのunzip
      command: tar zxvf /var/opt/data/nfs/jenkins_mvn/installer/apache-maven-3.3.3-bin.tar.gz -C /opt/.

    # ========================================================
    # mavenディレクトリを削除する(冪等性担保)
    # ========================================================
    - name: Mavenの削除
      command: rm -rf /opt/maven

    # ========================================================
    # mavenディレクトリmaven3.3.3をmavenにリネーム
    # ========================================================
    - name: Mavenのrename
      command: mv /opt/apache-maven-3.3.3 /opt/maven

    # ========================================================
    # mavenディレクトリmaven3.3.3をmavenにリネームして環境変数に適用
    # ========================================================
    - name: Mavenのrename
      lineinfile: state=present dest=/etc/profile.d/profile_init.sh regexp='^export MAVEN_HOME=/opt/maven' line='export MAVEN_HOME=/opt/maven' create=yes
    - lineinfile: state=present dest=/etc/profile.d/profile_init.sh regexp='^export PATH=${MAVEN_HOME}/bin:${PATH}' line='export PATH=${MAVEN_HOME}/bin:${PATH}' create=yes
    - shell: /etc/profile.d/profile_init.sh


    # ========================================================
    # Jenkinsファイルを削除する
    # ========================================================
    - name: jenkinsの削除
      command: rm -rf /opt/tomcat/webapps/jenkins.war

    # ========================================================
    # Jenkins.warをtomcat webappp配下にコピーする
    # ========================================================
    - name: jenkinsの配置
      shell: cp /var/opt/data/nfs/jenkins_mvn/installer/jenkins.war /opt/tomcat/webapps/.


    # ========================================================
    # Jenkisnを起動状態にする
    # ========================================================
    - name: jenkinsの配置
      service: name=tomcat enabled=yes state=restarted
