# =======================================================================
# openvpnをインストールしてCA/SERVER/client証明書を作成する(openvpn.yml
# =======================================================================
---
- hosts: adminserv01
  sudo: no
  remote_user: root
  vars_files:
    - ../vars/yum.yml
    - ../vars/enviroment.yml
  tasks:
    # ========================================================
    # 再インストールしたい場合
    # ========================================================
    - name: 再インストールする場合
      shell: "rm -rf /etc/openvpn;rm /var/opt/data/nfs/output/*"
      when: reinstall_openvpn == 'yes'
      ignore_errors: true

    # ========================================================
    # openvpnのインストール冪等性を/etc/openvpn/easy-rsa/commit
    # が正しく生成されたら作成しないとする
    #(本当はもっと考えるべきなんだろうどけ...)
    # ========================================================
    - name: /etc/openvpn/easy-rsa/commitにファイルが存在するか確認(このファイルがあるということは設定が完了している事とする)
      stat: path=/etc/openvpn/easy-rsa/commit
      register: rsa_exist



    # ========================================================
    # openvpnをyumリポジトリよりインストールする
    # ========================================================
    - name: openvpnパッケージインストトール
      yum: name={{rpm.package.openvpn }} state=present



    # ========================================================
    # 秘密鍵/公開鍵証明書の作成はeasy-rsa2を使用する。(yumリポジトリよりインストール)
    # ========================================================
    - name: easy_rsaパッケージインストトール
      yum: name={{rpm.package.easy_rsa }} state=present

    - name: easy-rsaディレクトリの作成
      file: path=/etc/openvpn/easy-rsa state=directory owner=root group=root mode=0700

    # ========================================================
    # openvpnのログは/var/log/openvpnに出力するようにする為先に作成
    # ========================================================
    - name: ログフォルダ作成
      file: state=directory owner=root group=root mode=0660 path=/var/log/openvpn


    # ========================================================
    # openvpnを一旦止める
    # ========================================================
    - name: 一旦サービスを無効にする。
      service: name=openvpn@server enabled=no state=stopped
      when: not rsa_exist.stat.exists
      ignore_errors: True

    # ========================================================
    # easy-rsaを/etc/openvpn配下にコピー
    # ========================================================
    - name: easy-rsaのコピー
      shell: cp /usr/share/easy-rsa/2.0/* /etc/openvpn/easy-rsa/.
      when: not rsa_exist.stat.exists


    # ========================================================
    # 先にserver.confを/etc/openvpn/をコピーしておく。
    # server.confは作成済であることとする。
    # ========================================================
    - name: OpenVPNサーバの設定ファイルを配置
      shell: cp /var/opt/data/nfs/openvpn/settings/server.conf /etc/openvpn/server.conf
      when: not rsa_exist.stat.exists

    # ========================================================
    # VPN_セグメント/クライアントのLANアドレスを置換する
    # ========================================================
    - name: 設定ファイルの環境固有値を置換
      replace:
        dest=/var/opt/data/nfs/openvpn/settings/server.conf
        regexp=<<CLIENT_ROUTE>>
        replace={{openvpn.client_route}}
      when: not rsa_exist.stat.exists
    - replace:
        dest=/var/opt/data/nfs/openvpn/settings/server.conf
        regexp=<<VPN_NETWORK>>
        replace={{openvpn.vpn_network}}
      when: not rsa_exist.stat.exists


    # ========================================================
    # varsファイルは証明書の有効期限やデフォルトのOU等の情報を記述しておく
    # ========================================================
    - name: Easy-RSAの編集したvarsファイルをコピーする
      shell: cp /var/opt/data/nfs/openvpn/settings/vars /etc/openvpn/easy-rsa/vars
      when: not rsa_exist.stat.exists

    # ========================================================
    # openvpnの証明書作成(easy-rsaのbuild-keyコマンド等)はすべて対話型であるためexpectコマンドを使用して
    # コマンドのQに対してAを記述しておく
    # ========================================================
    - name: CA証明書とサーバ証明書は対話型の為expectで対話処理を自動化する(expectコマンド群をコピー）
      shell: cp /var/opt/data/nfs/openvpn/settings/exec*.exp /etc/openvpn/easy-rsa/.
      when: not rsa_exist.stat.exists

    # ========================================================
    # CA秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: 権限付与(CA_EXPECT)
      file: state=file owner=root group=root mode=0700 path=/etc/openvpn/easy-rsa/exec_ca.exp
      when: not rsa_exist.stat.exists

    # ========================================================
    # Server秘密鍵/公開鍵証明書　作成用の/exec_serverの配置と権限(755)を付与する
    # ========================================================
    - name: 権限付与(SERVER_EXPECT)
      file: state=file owner=root group=root mode=0700 path=/etc/openvpn/easy-rsa/exec_server.exp
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_clientの配置と権限(755)を付与する
    # ========================================================
    - name: 権限付与(CLIENT_EXPECT)
      file: state=file owner=root group=root mode=0700 path=/etc/openvpn/easy-rsa/exec_client.exp
      when: not rsa_exist.stat.exists

    # ========================================================
    # CAの作成(CA用の公開鍵証明書と秘密鍵)
    # ========================================================
    - name: CA証明書(公開鍵/秘密鍵)を作成
      shell: . ./vars;./clean-all;./exec_ca.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # ディフィー・ヘルマン鍵共有のパラ－メータを作成(セッション共通鍵生成パラメータ)
    # ========================================================
    - name: ディフィー・ヘルマン鍵共有のパラ－メータを作成(セッション共通鍵生成パラメータ)
      shell: . ./vars;./build-dh chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # サーバ公開証明書と秘密鍵作成
    # ========================================================
    - name: サーバ証明書(公開鍵/秘密鍵)を作成
      shell: . ./vars;./exec_server.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: クライアント証明書(公開鍵/秘密鍵)を作成(uemura)
      shell: . ./vars;export OPENVPN_CLINET_NM=uemura;./exec_client.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: クライアント証明書(公開鍵/秘密鍵)を作成(user01)
      shell: . ./vars;export OPENVPN_CLINET_NM=user01;./exec_client.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: クライアント証明書(公開鍵/秘密鍵)を作成(user02)
      shell: . ./vars;export OPENVPN_CLINET_NM=user02;./exec_client.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: 失効リスト作成用ユーザー(revoke)のクライアント証明書(公開鍵/秘密鍵)を作成する
      shell: . ./vars;export OPENVPN_CLINET_NM=revoke;./exec_client.exp chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: 失効リスト作成用ユーザー(revoke)を失効させる(ここではステータスコード2がかえる(無視してよい))
      shell: . ./vars;./revoke-full revoke chdir=/etc/openvpn/easy-rsa/
      when: not rsa_exist.stat.exists
      register: revoke_chk
      failed_when: revoke_chk.rc not in [0, 2]

#    easy-rsa2では証明書有効性のcrl.pemは初回失効時作成される
#    - name: 証明書失効リストを作成する
#      shell: . ./vars;./gen-crl chdir=/etc/openvpn/easy-rsa/
#      when: not rsa_exist.stat.exists

    # ========================================================
    # 作成したサーバ証明書/キー/dh2048キーを所定の場所にコピー
    # ========================================================
    - name: 作成した鍵や失効リストを/etc/openvpn配下にコピー
      shell: cp ./ca.crt ./server.crt ./server.key ./crl.pem ./dh2048.pem ./index.txt ../../. chdir=/etc/openvpn/easy-rsa/keys
      when: not rsa_exist.stat.exists

    # ========================================================
    # 作成したサーバ証明書/キー/dh2048キーを所定の場所にコピー
    # ========================================================
    - name: ファイルのパーミッションを変更
      file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/ca.crt
      when: not rsa_exist.stat.exists
    - file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/server.key
      when: not rsa_exist.stat.exists

    - file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/server.crt
      when: not rsa_exist.stat.exists

    - file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/crl.pem
      when: not rsa_exist.stat.exists

    - file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/dh2048.pem
      when: not rsa_exist.stat.exists

    - file:
        state=file owner=root group=root mode=0500 path=/etc/openvpn/index.txt
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵を圧縮する
    # ========================================================
    - name: tar-gzip化(uemura)
      shell: mkdir uemura;cp ./uemura.* ./uemura/.;tar cvzf uemura.tar.gz ./uemura chdir=/etc/openvpn/easy-rsa/keys
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵を圧縮する
    # ========================================================
    - name: tar-gzip化(user01)
      shell: mkdir user01;cp ./user01.* ./user01/.;tar cvzf user01.tar.gz ./user01 chdir=/etc/openvpn/easy-rsa/keys
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵を圧縮する
    # ========================================================
    - name: tar-gzip化(user02)
      shell: mkdir user02;cp ./user02.* ./user02/.;tar cvzf user02.tar.gz ./user02 chdir=/etc/openvpn/easy-rsa/keys
      when: not rsa_exist.stat.exists

    # ========================================================
    # 圧縮したクライアント証明書を所定のディレクトリに移動する
    # ========================================================
    - name: 出力ファイルフォルダにクライアントキーを配置
      shell: mv ./*.tar.gz /var/opt/data/nfs/output/. chdir=/etc/openvpn/easy-rsa/keys
      when: not rsa_exist.stat.exists

    # ========================================================
    # 正常終了したフラグ用のファイルを配置
    # ========================================================
    - name: 正常完了フラグ
      shell: touch /etc/openvpn/easy-rsa/commit
      when: not rsa_exist.stat.exists

    # ========================================================
    # クライアント秘密鍵/公開鍵証明書　作成用の/exec_caの配置と権限(755)を付与する
    # ========================================================
    - name: オープンVPNサーバサービスを再起動する
      service: name=openvpn@server enabled=yes state=restarted

