# ========================================================
# firewalldの設定(firewalld.yml)
# ========================================================
---
# ========================================================
# 管理サーバ(adminserv01)にFirewall NFS/VPN/TOMCAT/MariaDB設定
# ========================================================
- hosts: adminserv01
  sudo: no
  remote_user: root
  vars_files:
    - ../vars/service.yml
    - ../vars/enviroment.yml
  tasks:
    - name: firewall再起動
      service: name=firewalld enabled=yes state=restarted
    # ========================================================
    # trustedゾーン(tun0オープンVPN)
    # ========================================================
    - name: opevpnのインターフェースのゾーンをtrustedゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd --permanent --zone=trusted --change-interface={{nic.vpn}}"
#    - shell: "firewall-cmd --zone=trusted --change-interface={{nic.vpn}}"
      shell: nmcli conn mod {{nic.vpn}} connection.zone trusted

    - name: trustedゾーンにipmasqueradeを設定
      shell: "firewall-cmd --permanent --zone=trusted --add-masquerade"
    - shell: "firewall-cmd --zone=trusted --add-masquerade"


    # ========================================================
    # ・dmzゾーン外部接続(enp0s9))の設定はopenVPNのみ通す
    # ========================================================
    - name: 外部接続用ののインターフェースをpublicゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd  --permanent --zone=dmz --change-interface={{nic.outer}}"
#    - shell: "firewall-cmd --zone=dmz --change-interface={{nic.outer}}"
      shell: nmcli conn mod {{nic.outer}} connection.zone dmz

    - name: SSHの不許可
      firewalld:
        service=ssh
        zone="dmz"
        permanent=true
        state=disabled
        immediate=yes

    - name: OPENVPNの許可
      firewalld:
        service={{ system.service.openvpn.name }}
        zone="dmz"
        permanent=true
        state=enabled
        immediate=yes

    # ========================================================
    # ・internalゾーン内部接続(enp0s8))の設定
    # ========================================================
    - name: 内部接続用ののインターフェースをpublicゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd  --permanent --zone=internal --change-interface={{nic.inner}}"
#    - shell: "firewall-cmd --zone=internal --change-interface={{nic.inner}}"
      shell: nmcli conn mod {{nic.inner}} connection.zone internal

    - name: dhcpv6-clientの不許可
      firewalld:
        service=dhcpv6-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: ipp-clientの不許可
      firewalld:
        service=ipp-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: mdnsの不許可
      firewalld:
        service=mdns
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: samba-clientの不許可
      firewalld:
        service=samba-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: sshの許可
      firewalld:
        service=ssh
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: HTTPの許可
      firewalld:
        service={{ system.service.http.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: TOMCATの許可
      firewalld:
        service={{ system.service.tomcat.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: TOMCAT-AJPの許可
      firewalld:
        service={{ system.service.tomcatajp.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: RCP-BIND(NFS)の許可
      firewalld:
        service={{ system.service.rpcbind.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: NFS(NFS)の許可
      firewalld:
        service={{ system.service.nfs.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: seleniumの許可
      firewalld:
        service={{ system.service.selenium.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: mysqlの許可
      firewalld:
        service={{ system.service.mysql.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    # ========================================================
    # ・リロード
    # ========================================================
    - name: firewall再起動
      shell: "firewall-cmd --reload"
    - service: name=firewalld enabled=yes state=restarted




# ========================================================
# APサーバ(apserv01)
# ========================================================
- hosts: apserv01
  sudo: no
  remote_user: root
  vars_files:
    - ../vars/service.yml
    - ../vars/enviroment.yml
  tasks:
    - name: firewall再起動
      service: name=firewalld enabled=yes state=restarted

    # ========================================================
    # ・dmzゾーン外部接続(enp0s9))の設定はHTTP/HTTPSのみ通す
    # ========================================================
    - name: 外部接続用ののインターフェースをdmzゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd --permanent --zone=dmz --change-interface={{nic.outer}}"
#    - shell: "firewall-cmd --zone=dmz --change-interface={{nic.outer}}"
      shell: nmcli conn mod {{nic.outer}} connection.zone dmz

    - name: SSHの不許可
      firewalld:
        service=ssh
        zone="dmz"
        permanent=true
        state=disabled
        immediate=yes

    - name: HTTPの許可
      firewalld:
        service={{ system.service.http.name }}
        zone="dmz"
        permanent=true
        state=enabled
        immediate=yes

    - name: HTTPSの許可
      firewalld:
        service={{ system.service.https.name }}
        zone="dmz"
        permanent=true
        state=enabled
        immediate=yes

    # ========================================================
    # ・internalゾーン内部接続(enp0s8))の設定
    # ========================================================
    - name: 内部接続用ののインターフェースをinternalゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd --permanent --zone=internal --change-interface={{nic.inner}}"
#    - shell: "firewall-cmd --zone=internal --change-interface={{nic.inner}}"
      shell: nmcli conn mod {{nic.inner}} connection.zone internal

    - name: dhcpv6-clientの不許可
      firewalld:
        service=dhcpv6-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: ipp-clientの不許可
      firewalld:
        service=ipp-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: mdnsの不許可
      firewalld:
        service=mdns
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: samba-clientの不許可
      firewalld:
        service=samba-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: sshの許可
      firewalld:
        service=ssh
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: HTTPの許可
      firewalld:
        service={{ system.service.http.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: HTTPSの許可
      firewalld:
        service={{ system.service.https.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: TOMCATの許可
      firewalld:
        service={{ system.service.tomcat.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: TOMCATAJPの許可
      firewalld:
        service={{ system.service.tomcatajp.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: NTPの許可
      firewalld:
        service={{ system.service.ntp.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    # ========================================================
    # ・リロード
    # ========================================================
    - name: firewall再起動
      shell: "firewall-cmd --reload"
    - service: name=firewalld enabled=yes state=restarted




# ========================================================
# DBサーバ(dbserv01)
# ========================================================
- hosts: dbserv01
  sudo: no
  remote_user: root
  vars_files:
    - ../vars/service.yml
    - ../vars/enviroment.yml
  tasks:
    - name: firewall再起動
      service: name=firewalld enabled=yes state=restarted
    # ========================================================
    # ・blockゾーン外部接続(enp0s9))の設定はすべてを遮断する
    # ========================================================
    - name: 外部接続用ののインターフェースをblockゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd --permanent --zone=block --change-interface={{nic.outer}}"
#      shell: "firewall-cmd --zone=block --change-interface={{nic.outer}}"
      shell: nmcli conn mod {{nic.outer}} connection.zone block



    # ========================================================
    # ・internalゾーン内部接続(enp0s8))の設定
    # ========================================================
    - name: 内部接続用ののインターフェースをinternalゾーンに変更
#      cent7.2ではchange-interfaceがfirewall-cmdで永続化出来ないのでnmcliで実行
#      shell: "firewall-cmd --permanent --zone=internal --change-interface={{nic.inner}}"
#      shell: "firewall-cmd --zone=internal --change-interface={{nic.inner}}"
      shell: nmcli conn mod {{nic.inner}} connection.zone internal

    - name: dhcpv6-clientの不許可
      firewalld:
        service=dhcpv6-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: ipp-clientの不許可
      firewalld:
        service=ipp-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: mdnsの不許可
      firewalld:
        service=mdns
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: samba-clientの不許可
      firewalld:
        service=samba-client
        zone="internal"
        permanent=true
        state=disabled
        immediate=yes

    - name: sshの許可
      firewalld:
        service=ssh
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    - name: mysqlの許可
      firewalld:
        service={{ system.service.mysql.name }}
        zone="internal"
        permanent=true
        state=enabled
        immediate=yes

    # ========================================================
    # ・リロード
    # ========================================================
    - name: firewall再起動
      shell: "firewall-cmd --reload"
    - service: name=firewalld enabled=yes state=restarted


