# ========================================================
# locate用のファイル・データベースの更新とパッケージの更新(finish.yml)
# ========================================================
---
- hosts: all
  sudo: no
  remote_user: root
  tasks:
    # ========================================================
    # locate用のファイル・データベースの更新
    # updatedbは時間のかかる可能性がある為非同期処理する
    # ========================================================
    - name: locateのデータベース更新
      shell: updatedb
      async: 1
      poll: 0
    # ========================================================
    # yumパッケージの更新
    # ========================================================
    - name: パッケージ全アップデート
      yum: name=* state=latest
